In [25]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [20]:
df = pd.read_csv("Insurance_MLR.csv")
df

age  height  weight  premium
0   25  162.56      70    20000
1   30  172.72      95    35000
2   35  167.64      78    41000
3   40     NaN     110    60000
4   45  157.48      86    70000

In [21]:
# Handle Missing value
mean_height = df.height.mean()

In [22]:
df.height = df.height.fillna(mean_height)

In [23]:
df

age  height  weight  premium
0   25  162.56      70    20000
1   30  172.72      95    35000
2   35  167.64      78    41000
3   40  165.10     110    60000
4   45  157.48      86    70000

In [26]:
reg = linear_model.LinearRegression()

In [28]:
reg.fit(df[['age','height','weight']],df['premium'])

LinearRegression()

In [29]:
reg.coef_

array([2182.25806452, -303.74227415,  223.11827957])

In [30]:
reg.intercept_

-620.9677419354921

In [31]:
reg.predict([[30,162,80]])

C:\Users\hp\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([33489.98814664])

In [32]:
reg.predict([[50,180,70]])

C:\Users\hp\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([69436.60570654])